"""Add claimed field for fake user purposes

Revision ID: 2cb2db7089f4
Revises: 9c1e52a780a7
Create Date: 2016-08-22 11:41:56.775928

"""

# revision identifiers, used by Alembic.
revision = '2cb2db7089f4'
down_revision = '9c1e52a780a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myuser', sa.Column('claimed', sa.Boolean(), nullable=True))
    op.create_index('aga_id__claimed', 'myuser', ['aga_id', 'claimed'], unique=True)
    op.drop_constraint('myuser_aga_id_key', 'myuser', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('myuser_aga_id_key', 'myuser', ['aga_id'])
    op.drop_index('aga_id__claimed', table_name='myuser')
    op.drop_column('myuser', 'claimed')
    ### end Alembic commands ###
