"""add index to Rating.created

Revision ID: 31163dd1dbbb
Revises: 01e860788b42
Create Date: 2017-01-01 15:00:04.551046

"""

# revision identifiers, used by Alembic.
revision = '31163dd1dbbb'
down_revision = '01e860788b42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rating_created'), 'rating', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_created'), table_name='rating')
    ### end Alembic commands ###
