"""Initial migration

Revision ID: 9c1e52a780a7
Revises: None
Create Date: 2016-08-22 10:27:14.437689

"""

# revision identifiers, used by Alembic.
revision = '9c1e52a780a7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('go_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=180), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('myuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aga_id', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=25), nullable=True),
    sa.Column('current_login_ip', sa.String(length=25), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aga_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('go_server_admin',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['go_server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['myuser.id'], )
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['go_server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['myuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['myuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['myuser.id'], )
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('white_id', sa.Integer(), nullable=True),
    sa.Column('black_id', sa.Integer(), nullable=True),
    sa.Column('date_played', sa.DateTime(), nullable=True),
    sa.Column('date_reported', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=True),
    sa.Column('game_record', sa.LargeBinary(), nullable=True),
    sa.Column('game_url', sa.String(length=100), nullable=True),
    sa.Column('handicap', sa.Integer(), nullable=True),
    sa.Column('komi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['black_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['go_server.id'], ),
    sa.ForeignKeyConstraint(['white_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('roles_users')
    op.drop_table('rating')
    op.drop_table('player')
    op.drop_table('go_server_admin')
    op.drop_table('role')
    op.drop_table('myuser')
    op.drop_table('go_server')
    ### end Alembic commands ###
