"""Add not null constraints everywhere

Revision ID: ba6fefa33e22
Revises: 2cb2db7089f4
Create Date: 2016-09-12 23:50:53.526022

"""

# revision identifiers, used by Alembic.
revision = 'ba6fefa33e22'
down_revision = '2cb2db7089f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'black_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'date_played',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game', 'date_reported',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game', 'handicap',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'komi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('game', 'rated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('game', 'result',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('game', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'white_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('go_server', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('go_server', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('go_server', 'url',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('myuser', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('myuser', 'claimed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('myuser', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('myuser', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('player', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('player', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rating', 'sigma',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'sigma',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rating', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('player', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('myuser', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('myuser', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('myuser', 'claimed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('myuser', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('go_server', 'url',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('go_server', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('go_server', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('game', 'white_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'result',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('game', 'rated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('game', 'komi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('game', 'handicap',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'date_reported',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game', 'date_played',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game', 'black_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
