"""Replace User.claimed field with User.fake field

Revision ID: d767d9266a19
Revises: ba6fefa33e22
Create Date: 2016-10-24 15:47:04.987196

"""

# revision identifiers, used by Alembic.
revision = 'd767d9266a19'
down_revision = 'ba6fefa33e22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myuser', sa.Column('fake', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('aga_id__fake', 'myuser', ['aga_id', 'fake'], unique=True)
    op.drop_index('aga_id__claimed', table_name='myuser')
    op.drop_column('myuser', 'claimed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myuser', sa.Column('claimed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('aga_id__claimed', 'myuser', ['aga_id', 'claimed'], unique=True)
    op.drop_index('aga_id__fake', table_name='myuser')
    op.drop_column('myuser', 'fake')
    ### end Alembic commands ###
